#
# Jekyll configuration
#
#destination: ./_site
auto:        false
lsi:         false # better related posts
server_port: 8080
pygments:    true
markdown:    maruku
#permalink:   none
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

#
# Site configuration
#
url:          http://localhost:8080/
title:        Compojure on GAE
description:  Deploying a Clojure web app to Google App Engine
keywords:     clojure, compojure, ring, app engine, gae
author:       Christian Berg
email:        berg.christian@gmail.com
analytics_id: # Google Analytics ID: UA-xxx-xxx
